# Documentation Build Makefile
# Use with GNU make
#
# Copyright (C) 2003 - 2006 The MARF Research and Development Group
#
# $Header: /cvsroot/marf/marf/doc/Makefile,v 1.6 2006/01/15 20:51:55 mokhov Exp $

all distro clean maintainer-clean:
	make -C src $@

# EOF
